- name: Download grml zsh config
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: $HOME/.zshrc
    mode: '0644'

- name: Copy homedir dotfiles
  copy:
    src: "{{ item }}"
    dest: "$HOME/.{{ item }}"
  with_items:
  - zshrc.pre
  - zshrc.local
  - tmux.conf
  - gitconfig
  - alacritty.yml


# Neovim config
- name: Make sure nvim dirs exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - $HOME/.local/share/nvim/site/autoload
  - $HOME/.config/nvim

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: $HOME/.local/share/nvim/site/autoload/plug.vim

- name: Copy nvim config
  copy:
    src: init.vim
    dest: $HOME/.config/nvim/init.vim
  register: nvim_config

- name: Run PlugInstall
  command: nvim --headless +PlugInstall +qa
  when: nvim_config.changed

