# 'brew tap'
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# set arguments for all 'brew install --cask' commands
cask_args appdir: "~/Applications", require_sha: true



# CLI
brew "cowsay"
brew "exa"
brew "fzf"
brew "gettext"
brew "gh"
brew "git"
brew "gpg"
brew "htop"
brew "httpie"
brew "jq"
brew "neovim"
brew "pv"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "wget"
brew "yq"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Coding
brew "autoconf"
brew "cmake"
brew "go"
brew "golangci-lint"
brew "node"
brew "nvm"
brew "postgres"
brew "python3"
brew "readline"
brew "redis"
brew "rust"
brew "sqlite"
brew "tree-sitter"
brew "llvm"

# Kubernetes
brew "argocd"
brew "grafana"
brew "k3d"
brew "kube-linter"
brew "kubeval"
brew "kustomize"
brew "prometheus"
brew "stern"
brew "tanka"
brew "wrk"
brew "yamllint"

# Terraform
brew "terraform"
brew "terraform-docs"
brew "tflint"

# Others
brew "awscli"
brew "gnupg"
brew "imagemagick"
brew "iperf"
brew "libevent"
brew "mas"
brew "msgpack"
brew "nmap"
brew "openssl"
brew "packer"
brew "pandoc"

# 'brew install --cask'
cask "discord"
cask "docker"
cask "drawio"
cask "google-chrome"
cask "keybase"
cask "slack"
cask "notion"
cask "vagrant"
cask "visual-studio-code"
cask "mactex"
cask "alacritty"
cask "homebrew/cask-fonts/font-jetbrains-mono-nerd-font"
