- hosts: all
  vars_files:
  - config.xvzf.yml

  # Preflight tasks
  pre_tasks:
  - import_tasks: tasks/preflight.yml
    tags: ['preflight']
  - import_tasks: tasks/rosetta2.yml
    when: setup_rosetta2
    tags: ['rosetta2']

  roles:
  - role: elliotweiser.osx-command-line-tools
  - role: brewfile
    tags: ['homebrew']
  - role: geerlingguy.mac.homebrew
    tags: ['homebrew']
  - role: geerlingguy.mac.mas
    when: mas_installed_apps
    tags: ['mas']
  - role: geerlingguy.mac.dock
    when: configure_dock
    tags: ['dock']
  - role: osx-setup
    tags: ['osx']
  - role: dotfiles
    tags: ['dotfiles']
